name: push
on: push
jobs:
  push-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hi
        run: |
          echo "Hello World on push!"
          cat hello.txt
